---
msmtp_accounts:
    # Account 1 - it was a real account for testing (but yandex now blocks it)
    # Uses Yandex app password limited to POP3, SMTP and IMAP
    - account:   yandex
      host:      smtp.yandex.com
      port:      587
      auth:      "on"
      from:      emailer-tests@yandex.com
      user:      emailer-tests@yandex.com
      password:  jhlrizltgkmnkkgm
      #Account 2
    - account:   mysmtp
      host:      smtp.example
      port:      587
      auth:      "on"
      from:      admin@example.org
      user:      myuser@example.org
      password:  plain-text-password2
      #Account 3
    - account:   gmail
      host:      smtp.gmail.com
      port:      587
      auth:      "on"
      from:      example@gmail.example
      user:      example@gmail.example
      password:  "some password"

msmtp_default_account: yandex
msmtp_domain:          yandex.com

## Logging (Select A) "syslog" or B) "file" logging or C) "no" log
msmtp_log:             file
## If using `syslog`, can be one of 'LOG_USER', 'LOG_MAIL', 'LOG_LOCAL0', â€¦, 'LOG_LOCAL7'.
msmtp_syslog_facility: "LOG_USER"
msmtp_logfile:         ~/.msmtp.log

## Aliases mail account ( only msmtp_alias_default is required the rest is optional )
msmtp_alias_default: emailer.tests@yandex.com
# Optional aliases for root and cron mails
# msmtp_alias_root:    emailer.tests@yandex.com
# msmtp_alias_cron:    emailer.tests@yandex.com

## Enable, after the the default smtp account is working
msmtp_send_test_mail: no
msmtp_test_mail_recipient: tester@example.org

## This will remove most other mail transfer agents such as postfix, exim,...!
msmtp_remove_mtas: no

## Permissions for the configuration file
msmtprc_owner: root
msmtprc_group: root
msmtprc_mode: 0644
