---
# enable or disable the application
gitlab_enabled: false
gitlab_available_externally: false

# directories
gitlab_data_directory: "{{ docker_home }}/gitlab"

# network
gitlab_hostname: "gitlab"
gitlab_port_http: "4080"
gitlab_port_https: "4443"
gitlab_port_ssh: "422"

# specs
gitlab_#memory: "4g"

# required definitions
gitlab_user_id: "998"
gitlab_group_id: "{{ gitlab_user_id }}"