---
# - name: Configure VPN for home network
- hosts: all
  become: true

  # vars_files:
  #   - custom.yml
  #   - secret.yml

  handlers:
    - name: Import global handlers
      ansible.builtin.import_tasks: handlers/main.yml

  roles:
    ###
    ### Requirements
    ###

    - role: system
      tags:
        - system

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    ###
    ### Applications
    ###

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns
        - cloudflare
      when: (cloudflare_ddns_enabled | default(False))

    ###
    ### Required Roles
    ###

    - role: wireguard
      tags:
        - wireguard

    - role: ssh
      tags:
        - ssh

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))