---
galaxy_info:
  author: Sylvain Prat
  role_name: snapraid
  namespace: sprat
  description: Install and configure SnapRAID â€” A backup program for disk arrays
  license: MIT
  company: none
  min_ansible_version: 2.3
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - snapraid
    - disk
    - backup
    - array

dependencies: []
