---
# Drive Mounts

### Parity Disk 0
parity0_mount_path: "/mnt/parity0"
parity0_uuid: ""

### Data Disk 0
disk0_mount_path: "/mnt/disk0"
disk0_uuid: ""

### Data Disk 1
disk1_mount_path: "/mnt/disk1"
disk1_uuid: ""

### Data Disk 2
disk2_mount_path: "/mnt/disk2"
disk2_uuid: ""

### Data Disk 3
disk3_mount_path: "/mnt/disk3"
disk3_uuid: ""