---
mergerfs_enabled: false

# Install mode: defines where to download and install the package from:
# - "github_releases": install from Mergerfs' GitHub releases
# - "package_manager": install from the Linux distribution package manager.
#   Note that the mergerfs package does not exists in all distributions, so it
#   may not work for you.
mergerfs_install_mode: github_releases

# Version to install: "latest" version or a specific version number, e.g. "2.28.2"
# This setting only applies in "github_releases" mode
mergerfs_version: latest

# Mergerfs mountpoints to create. For example:
# mergerfs_mounts:
#   - path: /mnt/storage
#     branches:
#       - /mnt/data*
#       - /mnt/other
#     options: allow_other,use_ino
mergerfs_mounts: []

# Url of the mergerfs GitHub releases page
mergerfs_github_releases_url: https://github.com/trapexit/mergerfs/releases
